# Generated by Django 5.2.1 on 2026-02-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="Unique session identifier", max_length=255
                    ),
                ),
                ("message", models.TextField(help_text="User's message")),
                ("response", models.TextField(help_text="Bot's response")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "retrieved_docs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of recipe IDs or content retrieved for context",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score of the response (0-1)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "-created_at"],
                        name="chatbot_cha_session_de6616_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="chatbot_cha_user_id_08561a_idx",
                    ),
                ],
            },
        ),
    ]
